<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ARO-MAB-2105" failures="1" tests="1" name="com.automationexercise.tests.TestCase24" time="32.078" errors="0" timestamp="2024-12-03T12:27:09 WAT" skipped="0">
  <testcase classname="com.automationexercise.tests.TestCase24" name="downloadInvoiceAfterPurchaseOrder" time="32.078">
    <failure message="Verify invoice is downloaded successfully. expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Verify invoice is downloaded successfully. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.automationexercise.tests.TestCase24.clickDownloadInvoiceButtonAndVerifyInvoiceIsDownloadedSuccessfully(TestCase24.java:62)
at com.automationexercise.tests.TestCase24.downloadInvoiceAfterPurchaseOrder(TestCase24.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- downloadInvoiceAfterPurchaseOrder -->
  <system-out/>
</testsuite> <!-- com.automationexercise.tests.TestCase24 -->
